version: '3.8'

services:
  # 1. Zookeeper : Nécessaire pour coordonner Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 2. Kafka : Le broker qui va stocker tes logs
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 3. Ton Ingestor de Logs
  log-ingestor:
    build:
      context: .
      dockerfile: log-ingestor/Dockerfile
    ports:
      - "9090:9090" # Port gRPC
      - "8080:8080" # Port Actuator
    depends_on:
      - kafka
    environment:
      # On pointe sur le nom du service "kafka" défini au-dessus
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      APP_KAFKA_TOPIC_NAME: "app-logs"
      # Optimisation Java 21 Virtual Threads
      JAVA_OPTS: "-Dspring.threads.virtual.enabled=true"